% th is pitch angle, ph is roll angle, ps is yaw angle. l is left, r is right.
function H = getOrientationHMatrix(phl,thl,psl,phr,thr,psr)
h11=-((8 *(cos(psl - psr)* cos(thl) *cos(thr) + sin(thl) *sin(thr))) ...
        /(2 *sin(phl)^2 *(3 + cos(2 *(psl - psr)) - 2 *cos(2 *thr) *sin(psl - psr)^2) ...
        + 4 *sin(2 *phl) *(-cos(thr)^2 *sin(2 *(psl - psr)) *sin(thl) + ...
        cos(thl) *sin(psl - psr) *sin(2 *thr)) + cos(phl)^2 * ...
        (8 *cos(thl)^2 *cos(thr)^2 - 2 *(-3 + cos(2 *(psl - psr)) + 2 *cos(psl - psr)^2 ...
        *cos(2 *thr)) *sin(thl)^2 + 4 *cos(psl - psr) *sin(2 *thl) *sin(2 *thr))));

    h12=(4 *cos(phl)^2 *cos(thr) *sin(psl - psr) + 2 *sin(2 *phl) *...
        (-cos(psl - psr) *cos(thr) *sin(thl) + cos(thl) *sin(thr)))/...
        (sin(phl)^2 *(3 + cos(2 *(psl - psr)) - 2 *cos(2 *thr) *sin(psl - psr)^2) ...
        + 2 *sin(2 *phl) *(-cos(thr)^2 *sin(2 *(psl - psr)) *sin(thl) + ...
        cos(thl) *sin(psl - psr) *sin(2 *thr)) + cos(phl)^2 *...
        (4 *cos(thl)^2 *cos(thr)^2 - (-3 + cos(2 *(psl - psr)) + ...
        2 *cos(psl - psr)^2 *cos(2 *thr)) *sin(thl)^2 + 2 *cos(psl - psr) *sin(2 *thl) *sin(2 *thr)));

    h13=(2 *cos(thr) *(cos(thl) *sin(2 *phl) *sin(psl - psr) + cos(phl)^2 *cos(psl - psr) *sin(2 *thl))...
        + 4 *(sin(phl)^2 + cos(phl)^2 *sin(thl)^2) *sin(thr))/...
        (sin(phl)^2 *(3 + cos(2 *(psl - psr)) - 2 *cos(2 *thr) *sin(psl - psr)^2) + ...
        2 *sin(2 *phl) *(-cos(thr)^2 *sin(2 *(psl - psr)) *sin(thl) + cos(thl) *sin(psl - psr) *sin(2 *thr))...
        + cos(phl)^2 *(4 *cos(thl)^2 *cos(thr)^2 - (-3 + cos(2 *(psl - psr)) + ...
        2 *cos(psl - psr)^2 *cos(2 *thr)) *sin(thl)^2 + 2 *cos(psl - psr) *sin(2 *thl) *sin(2 *thr)));

    h14=1;

    h15=(8 *(cos(psl - psr) *sin(phl) - cos(phl) *sin(psl - psr) *sin(thl))...
        *(cos(thr) *(sin(phl) *sin(psl - psr) + cos(phl) *cos(psl - psr) *sin(thl))...
        - cos(phl) *cos(thl) *sin(thr)))/(2 *sin(phl)^2 *(3 + cos(2 *(psl - psr)) ...
        -2 *cos(2 *thr) *sin(psl - psr)^2) + 4 *sin(2 *phl) *(-cos(thr)^2 *sin(2 *(psl - psr))...
        *sin(thl) + cos(thl) *sin(psl - psr) *sin(2 *thr)) + cos(phl)^2 ...
        *(8 *cos(thl)^2 *cos(thr)^2 - 2 *(-3 + cos(2 *(psl - psr)) + ...
        2 *cos(psl - psr)^2 *cos(2 *thr)) *sin(thl)^2 + 4 *cos(psl - psr) *sin(2 *thl) *sin(2 *thr)));

    h16=(-2 *cos(thr) *(cos(thl) *sin(2 *phl) *sin(psl - psr) + cos(phl)^2 *...
        cos(psl - psr) *sin(2 *thl)) - 4 *(sin(phl)^2 + cos(phl)^2 *sin(thl)^2) *sin(thr))/...
        (sin(phl)^2 *(3 + cos(2 *(psl - psr)) - 2 *cos(2 *thr) *sin(psl - psr)^2) + ...
        2 *sin(2 *phl) *(-cos(thr)^2 *sin(2 *(psl - psr)) *sin(thl) + cos(thl) *...
        sin(psl - psr) *sin(2 *thr)) + cos(phl)^2 *(4 *cos(thl)^2 *cos(thr)^2 - ...
        (-3 + cos(2 *(psl - psr)) + 2 *cos(psl - psr)^2 *cos(2 *thr)) *sin(thl)^2 + ...
        2 *cos(psl - psr) *sin(2 *thl) *sin(2 *thr)));

    h21=(-cos(phl) *cos(thr) *sin(psl - psr) + sin(phl) *(cos(psl - psr) *cos(thr) *sin(thl) ...
        - cos(thl) *sin(thr)))/(sqrt(1 - (cos(thr) *(sin(phl) *sin(psl - psr) + ...
        cos(phl) *cos(psl - psr) *sin(thl)) - cos(phl) *cos(thl) *sin(thr))^2));

    h22= -((cos(phl) *(cos(psl - psr) *cos(thl) *cos(thr) + sin(thl) *sin(thr)))/...
        (sqrt(1 - (cos(thr) *(sin(phl) *sin(psl - psr) + cos(phl) *cos(psl - psr) *sin(thl))...
        - cos(phl) *cos(thl) *sin(thr))^2)));

    h23=(cos(thr) *(-cos(psl - psr) *sin(phl) + cos(phl) *sin(psl - psr) *sin(thl)))/...
        (sqrt(1 - (cos(thr) *(sin(phl) *sin(psl - psr) + cos(phl) *cos(psl - psr) *sin(thl))...
        - cos(phl) *cos(thl) *sin(thr))^2));

    h24=0;

    h25=(sin(phl) *sin(psl - psr) *sin(thr) + cos(phl) *(cos(thl) *cos(thr) + ...
        cos(psl - psr) *sin(thl) *sin(thr)))/(sqrt(1 - (cos(thr) *(sin(phl) *sin(psl - psr) ...
        + cos(phl) *cos(psl - psr) *sin(thl)) - cos(phl) *cos(thl) *sin(thr))^2));

    h26=(cos(thr) *(cos(psl - psr) *sin(phl) - cos(phl) *sin(psl - psr) *sin(thl)))/...
        (sqrt(1 - (cos(thr) *(sin(phl) *sin(psl - psr) + cos(phl) *cos(psl - psr) *sin(thl)) ...
        - cos(phl) *cos(thl) *sin(thr))^2));

    h31=(cos(thr) *(sin(phl) *sin(psl - psr) + cos(phl) *cos(psl - psr) *sin(thl)) - ...
        cos(phl)* cos(thl)* sin(thr))/((cos(psl) *cos(psr) *cos(thl) *cos(thr) +...
        cos(thl) *cos(thr) *sin(psl) *sin(psr) + sin(thl) *sin(thr)) *...
        (1 + (cos(phl) *cos(thr) *sin(psl - psr) - sin(phl) *(cos(psl) *cos(psr) *cos(thr) *sin(thl) ...
        + cos(thr) *sin(psl) *sin(psr) *sin(thl) - cos(thl) *sin(thr)))^2/...
        (cos(psl) *cos(psr) *cos(thl) *cos(thr) + cos(thl) *cos(thr) *sin(psl)* sin(psr) + ...
        sin(thl) *sin(thr))^2));

    h32=(sin(phl) + ((cos(psl) *cos(psr) *cos(thr) *sin(thl) + cos(thr) *sin(psl) *sin(psr) *sin(thl)...
        - cos(thl) *sin(thr)) *(-cos(phl) *cos(thr) *sin(psl - psr) + sin(phl) *(cos(psl) *cos(psr)*...
        cos(thr) *sin(thl) + cos(thr) *sin(psl) *sin(psr) *sin(thl) - cos(thl)* sin(thr))))/...
        (cos(psl)* cos(psr) *cos(thl) *cos(thr) +cos(thl) *cos(thr) *sin(psl) *sin(psr) + ...
        sin(thl) *sin(thr))^2)/(1 + (cos(phl) *cos(thr) *sin(psl - psr) - sin(phl) *...
        (cos(psl)* cos(psr)* cos(thr) *sin(thl) + cos(thr) *sin(psl) *sin(psr) *sin(thl) - ...
        cos(thl) *sin(thr)))^2/(cos(psl) *cos(psr) *cos(thl) *cos(thr) + ...
        cos(thl) *cos(thr) *sin(psl) *sin(psr) + sin(thl) *sin(thr))^2);

    h33=-((cos(thr) *(sin(phl)* sin(psl - psr) *sin(thr) + cos(phl) *(cos(thl) *cos(thr) + ...
        cos(psl - psr) *sin(thl) *sin(thr))))/((cos(psl) *cos(psr) *cos(thl) *cos(thr) + ...
        cos(thl)* cos(thr) *sin(psl) *sin(psr) + sin(thl) *sin(thr))^2 *(1 + ...
        (cos(phl) *cos(thr) *sin(psl - psr) - sin(phl) *(cos(psl) *cos(psr)* cos(thr) *sin(thl)...
        + cos(thr) *sin(psl)* sin(psr) *sin(thl) - cos(thl) *sin(thr)))^2/...
        (cos(psl)* cos(psr) *cos(thl) *cos(thr) + cos(thl) *cos(thr) *sin(psl) *sin(psr) + ...
        sin(thl) *sin(thr))^2)));

    h34=0;

    h35=(sin(psl)* (-sin(phl) *sin(psr) + cos(phl) *cos(psr)* sin(thl)) - ...
        cos(psl)* (cos(psr)* sin(phl) + cos(phl) *sin(psr) *sin(thl)))/...
        ((cos(psl) *cos(psr) *cos(thl) *cos(thr) + cos(thl)* cos(thr) *sin(psl) *sin(psr)...
        + sin(thl)* sin(thr))^2 *(1 + (cos(phl) *cos(thr) *sin(psl - psr) - ...
        sin(phl) *(cos(psl) *cos(psr)* cos(thr)* sin(thl) + cos(thr) *sin(psl) *sin(psr)...
        *sin(thl) - cos(thl) *sin(thr)))^2/(cos(psl) *cos(psr) *cos(thl) *cos(thr) +...
        cos(thl) *cos(thr) *sin(psl) *sin(psr) + sin(thl) *sin(thr))^2));

    h36=(cos(thr) *(sin(phl) *sin(psl - psr) *sin(thr) + cos(phl) *(cos(thl) *cos(thr) + ...
        cos(psl - psr) *sin(thl) *sin(thr))))/((cos(psl) *cos(psr) *cos(thl) *cos(thr) +...
        cos(thl) *cos(thr) *sin(psl) *sin(psr) + sin(thl) *sin(thr))^2 *(1 + ...
        (cos(phl)* cos(thr) *sin(psl - psr) - sin(phl) *(cos(psl) *cos(psr) *cos(thr) *sin(thl)...
        + cos(thr) *sin(psl) *sin(psr) *sin(thl) - cos(thl) *sin(thr)))^2/...
        (cos(psl) *cos(psr) *cos(thl) *cos(thr) + cos(thl)* cos(thr) *sin(psl) *sin(psr) + ...
        sin(thl) *sin(thr))^2));
    H = [h11, h12, h13,h14,h15,h16;h21,h22,h23,h24,h25,h26;h31,h32,h33,h34,h35,h36];
end

